// Generated by gencpp from file morai_msgs/EgoVehicleStatus.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_EGOVEHICLESTATUS_H
#define MORAI_MSGS_MESSAGE_EGOVEHICLESTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct EgoVehicleStatus_
{
  typedef EgoVehicleStatus_<ContainerAllocator> Type;

  EgoVehicleStatus_()
    : header()
    , unique_id(0)
    , acceleration()
    , position()
    , velocity()
    , angular_velocity()
    , heading(0.0)
    , accel(0.0)
    , brake(0.0)
    , front_steer_angle(0.0)
    , rear_steer_angle(0.0)
    , lateral_offset(0.0)
    , tire_lateral_force_fl(0.0)
    , tire_lateral_force_fr(0.0)
    , tire_lateral_force_rl(0.0)
    , tire_lateral_force_rr(0.0)
    , side_slip_angle_fl(0.0)
    , side_slip_angle_fr(0.0)
    , side_slip_angle_rl(0.0)
    , side_slip_angle_rr(0.0)
    , tire_cornering_stiffness_fl(0.0)
    , tire_cornering_stiffness_fr(0.0)
    , tire_cornering_stiffness_rl(0.0)
    , tire_cornering_stiffness_rr(0.0)
    , distance_left_lane_boundary(0.0)
    , distance_right_lane_boundary(0.0)
    , cross_track_error(0.0)  {
    }
  EgoVehicleStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , unique_id(0)
    , acceleration(_alloc)
    , position(_alloc)
    , velocity(_alloc)
    , angular_velocity(_alloc)
    , heading(0.0)
    , accel(0.0)
    , brake(0.0)
    , front_steer_angle(0.0)
    , rear_steer_angle(0.0)
    , lateral_offset(0.0)
    , tire_lateral_force_fl(0.0)
    , tire_lateral_force_fr(0.0)
    , tire_lateral_force_rl(0.0)
    , tire_lateral_force_rr(0.0)
    , side_slip_angle_fl(0.0)
    , side_slip_angle_fr(0.0)
    , side_slip_angle_rl(0.0)
    , side_slip_angle_rr(0.0)
    , tire_cornering_stiffness_fl(0.0)
    , tire_cornering_stiffness_fr(0.0)
    , tire_cornering_stiffness_rl(0.0)
    , tire_cornering_stiffness_rr(0.0)
    , distance_left_lane_boundary(0.0)
    , distance_right_lane_boundary(0.0)
    , cross_track_error(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _unique_id_type;
  _unique_id_type unique_id;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _acceleration_type;
  _acceleration_type acceleration;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef double _heading_type;
  _heading_type heading;

   typedef float _accel_type;
  _accel_type accel;

   typedef float _brake_type;
  _brake_type brake;

   typedef float _front_steer_angle_type;
  _front_steer_angle_type front_steer_angle;

   typedef float _rear_steer_angle_type;
  _rear_steer_angle_type rear_steer_angle;

   typedef float _lateral_offset_type;
  _lateral_offset_type lateral_offset;

   typedef float _tire_lateral_force_fl_type;
  _tire_lateral_force_fl_type tire_lateral_force_fl;

   typedef float _tire_lateral_force_fr_type;
  _tire_lateral_force_fr_type tire_lateral_force_fr;

   typedef float _tire_lateral_force_rl_type;
  _tire_lateral_force_rl_type tire_lateral_force_rl;

   typedef float _tire_lateral_force_rr_type;
  _tire_lateral_force_rr_type tire_lateral_force_rr;

   typedef float _side_slip_angle_fl_type;
  _side_slip_angle_fl_type side_slip_angle_fl;

   typedef float _side_slip_angle_fr_type;
  _side_slip_angle_fr_type side_slip_angle_fr;

   typedef float _side_slip_angle_rl_type;
  _side_slip_angle_rl_type side_slip_angle_rl;

   typedef float _side_slip_angle_rr_type;
  _side_slip_angle_rr_type side_slip_angle_rr;

   typedef float _tire_cornering_stiffness_fl_type;
  _tire_cornering_stiffness_fl_type tire_cornering_stiffness_fl;

   typedef float _tire_cornering_stiffness_fr_type;
  _tire_cornering_stiffness_fr_type tire_cornering_stiffness_fr;

   typedef float _tire_cornering_stiffness_rl_type;
  _tire_cornering_stiffness_rl_type tire_cornering_stiffness_rl;

   typedef float _tire_cornering_stiffness_rr_type;
  _tire_cornering_stiffness_rr_type tire_cornering_stiffness_rr;

   typedef float _distance_left_lane_boundary_type;
  _distance_left_lane_boundary_type distance_left_lane_boundary;

   typedef float _distance_right_lane_boundary_type;
  _distance_right_lane_boundary_type distance_right_lane_boundary;

   typedef float _cross_track_error_type;
  _cross_track_error_type cross_track_error;





  typedef boost::shared_ptr< ::morai_msgs::EgoVehicleStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::EgoVehicleStatus_<ContainerAllocator> const> ConstPtr;

}; // struct EgoVehicleStatus_

typedef ::morai_msgs::EgoVehicleStatus_<std::allocator<void> > EgoVehicleStatus;

typedef boost::shared_ptr< ::morai_msgs::EgoVehicleStatus > EgoVehicleStatusPtr;
typedef boost::shared_ptr< ::morai_msgs::EgoVehicleStatus const> EgoVehicleStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::EgoVehicleStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::EgoVehicleStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::EgoVehicleStatus_<ContainerAllocator1> & lhs, const ::morai_msgs::EgoVehicleStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.unique_id == rhs.unique_id &&
    lhs.acceleration == rhs.acceleration &&
    lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.angular_velocity == rhs.angular_velocity &&
    lhs.heading == rhs.heading &&
    lhs.accel == rhs.accel &&
    lhs.brake == rhs.brake &&
    lhs.front_steer_angle == rhs.front_steer_angle &&
    lhs.rear_steer_angle == rhs.rear_steer_angle &&
    lhs.lateral_offset == rhs.lateral_offset &&
    lhs.tire_lateral_force_fl == rhs.tire_lateral_force_fl &&
    lhs.tire_lateral_force_fr == rhs.tire_lateral_force_fr &&
    lhs.tire_lateral_force_rl == rhs.tire_lateral_force_rl &&
    lhs.tire_lateral_force_rr == rhs.tire_lateral_force_rr &&
    lhs.side_slip_angle_fl == rhs.side_slip_angle_fl &&
    lhs.side_slip_angle_fr == rhs.side_slip_angle_fr &&
    lhs.side_slip_angle_rl == rhs.side_slip_angle_rl &&
    lhs.side_slip_angle_rr == rhs.side_slip_angle_rr &&
    lhs.tire_cornering_stiffness_fl == rhs.tire_cornering_stiffness_fl &&
    lhs.tire_cornering_stiffness_fr == rhs.tire_cornering_stiffness_fr &&
    lhs.tire_cornering_stiffness_rl == rhs.tire_cornering_stiffness_rl &&
    lhs.tire_cornering_stiffness_rr == rhs.tire_cornering_stiffness_rr &&
    lhs.distance_left_lane_boundary == rhs.distance_left_lane_boundary &&
    lhs.distance_right_lane_boundary == rhs.distance_right_lane_boundary &&
    lhs.cross_track_error == rhs.cross_track_error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::EgoVehicleStatus_<ContainerAllocator1> & lhs, const ::morai_msgs::EgoVehicleStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::EgoVehicleStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::EgoVehicleStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::EgoVehicleStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::EgoVehicleStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::EgoVehicleStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::EgoVehicleStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::EgoVehicleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3d9f65cf9e5cbc5fd966757559f49b2";
  }

  static const char* value(const ::morai_msgs::EgoVehicleStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3d9f65cf9e5cbc5ULL;
  static const uint64_t static_value2 = 0xfd966757559f49b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::EgoVehicleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/EgoVehicleStatus";
  }

  static const char* value(const ::morai_msgs::EgoVehicleStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::EgoVehicleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# EgoVehicleStatus\n"
"# Status telemetry of the ego vehicle for closed-loop control.\n"
"# Topic: /Ego_topic\n"
"\n"
"Header header\n"
"int32 unique_id  # Object unique id\n"
"geometry_msgs/Vector3 acceleration  # Acceleration vector [m/s^2]\n"
"geometry_msgs/Vector3 position  # Current position in ENU coordinates [m]\n"
"geometry_msgs/Vector3 velocity  # Velocity vector [m/s]\n"
"geometry_msgs/Vector3 angular_velocity  # [deg/s] \n"
"\n"
"float64 heading  # Vehicle heading [deg]\n"
"float32 accel  # Accelerator pedal, range 0~1\n"
"float32 brake  # Brake pedal, range 0~1\n"
"float32 front_steer_angle  # Front wheel angle [deg]\n"
"float32 rear_steer_angle  # Rear wheel angle [deg]\n"
"float32 lateral_offset  # Lateral offset from reference\n"
"\n"
"float32 tire_lateral_force_fl  # Front-left tire lateral force\n"
"float32 tire_lateral_force_fr  # Front-right tire lateral force\n"
"float32 tire_lateral_force_rl  # Rear-left tire lateral force\n"
"float32 tire_lateral_force_rr  # Rear-right tire lateral force\n"
"\n"
"float32 side_slip_angle_fl  # Front-left side slip angle\n"
"float32 side_slip_angle_fr  # Front-right side slip angle\n"
"float32 side_slip_angle_rl  # Rear-left side slip angle\n"
"float32 side_slip_angle_rr  # Rear-right side slip angle\n"
"\n"
"float32 tire_cornering_stiffness_fl  # Front-left cornering stiffness\n"
"float32 tire_cornering_stiffness_fr  # Front-right cornering stiffness\n"
"float32 tire_cornering_stiffness_rl  # Rear-left cornering stiffness\n"
"float32 tire_cornering_stiffness_rr  # Rear-right cornering stiffness\n"
"\n"
"float32 distance_left_lane_boundary  # Distance from left lane boundary [m]\n"
"float32 distance_right_lane_boundary  # Distance from right lane boundary [m]\n"
"float32 cross_track_error  # Distance from lane center, right-positive [m]\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::morai_msgs::EgoVehicleStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::EgoVehicleStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.unique_id);
      stream.next(m.acceleration);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.angular_velocity);
      stream.next(m.heading);
      stream.next(m.accel);
      stream.next(m.brake);
      stream.next(m.front_steer_angle);
      stream.next(m.rear_steer_angle);
      stream.next(m.lateral_offset);
      stream.next(m.tire_lateral_force_fl);
      stream.next(m.tire_lateral_force_fr);
      stream.next(m.tire_lateral_force_rl);
      stream.next(m.tire_lateral_force_rr);
      stream.next(m.side_slip_angle_fl);
      stream.next(m.side_slip_angle_fr);
      stream.next(m.side_slip_angle_rl);
      stream.next(m.side_slip_angle_rr);
      stream.next(m.tire_cornering_stiffness_fl);
      stream.next(m.tire_cornering_stiffness_fr);
      stream.next(m.tire_cornering_stiffness_rl);
      stream.next(m.tire_cornering_stiffness_rr);
      stream.next(m.distance_left_lane_boundary);
      stream.next(m.distance_right_lane_boundary);
      stream.next(m.cross_track_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EgoVehicleStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::EgoVehicleStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::EgoVehicleStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "unique_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.unique_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acceleration: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.acceleration);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angular_velocity: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "accel: ";
    Printer<float>::stream(s, indent + "  ", v.accel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "brake: ";
    Printer<float>::stream(s, indent + "  ", v.brake);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "front_steer_angle: ";
    Printer<float>::stream(s, indent + "  ", v.front_steer_angle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rear_steer_angle: ";
    Printer<float>::stream(s, indent + "  ", v.rear_steer_angle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lateral_offset: ";
    Printer<float>::stream(s, indent + "  ", v.lateral_offset);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tire_lateral_force_fl: ";
    Printer<float>::stream(s, indent + "  ", v.tire_lateral_force_fl);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tire_lateral_force_fr: ";
    Printer<float>::stream(s, indent + "  ", v.tire_lateral_force_fr);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tire_lateral_force_rl: ";
    Printer<float>::stream(s, indent + "  ", v.tire_lateral_force_rl);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tire_lateral_force_rr: ";
    Printer<float>::stream(s, indent + "  ", v.tire_lateral_force_rr);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "side_slip_angle_fl: ";
    Printer<float>::stream(s, indent + "  ", v.side_slip_angle_fl);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "side_slip_angle_fr: ";
    Printer<float>::stream(s, indent + "  ", v.side_slip_angle_fr);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "side_slip_angle_rl: ";
    Printer<float>::stream(s, indent + "  ", v.side_slip_angle_rl);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "side_slip_angle_rr: ";
    Printer<float>::stream(s, indent + "  ", v.side_slip_angle_rr);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tire_cornering_stiffness_fl: ";
    Printer<float>::stream(s, indent + "  ", v.tire_cornering_stiffness_fl);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tire_cornering_stiffness_fr: ";
    Printer<float>::stream(s, indent + "  ", v.tire_cornering_stiffness_fr);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tire_cornering_stiffness_rl: ";
    Printer<float>::stream(s, indent + "  ", v.tire_cornering_stiffness_rl);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tire_cornering_stiffness_rr: ";
    Printer<float>::stream(s, indent + "  ", v.tire_cornering_stiffness_rr);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "distance_left_lane_boundary: ";
    Printer<float>::stream(s, indent + "  ", v.distance_left_lane_boundary);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "distance_right_lane_boundary: ";
    Printer<float>::stream(s, indent + "  ", v.distance_right_lane_boundary);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cross_track_error: ";
    Printer<float>::stream(s, indent + "  ", v.cross_track_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_EGOVEHICLESTATUS_H
