// Generated by gencpp from file morai_msgs/MoraiWaitForTickSrvResponse.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_MORAIWAITFORTICKSRVRESPONSE_H
#define MORAI_MSGS_MESSAGE_MORAIWAITFORTICKSRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <morai_msgs/WaitForTickResponse.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct MoraiWaitForTickSrvResponse_
{
  typedef MoraiWaitForTickSrvResponse_<ContainerAllocator> Type;

  MoraiWaitForTickSrvResponse_()
    : response()  {
    }
  MoraiWaitForTickSrvResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef  ::morai_msgs::WaitForTickResponse_<ContainerAllocator>  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoraiWaitForTickSrvResponse_

typedef ::morai_msgs::MoraiWaitForTickSrvResponse_<std::allocator<void> > MoraiWaitForTickSrvResponse;

typedef boost::shared_ptr< ::morai_msgs::MoraiWaitForTickSrvResponse > MoraiWaitForTickSrvResponsePtr;
typedef boost::shared_ptr< ::morai_msgs::MoraiWaitForTickSrvResponse const> MoraiWaitForTickSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3e870eaeeef51ae05e735f139f5a34a";
  }

  static const char* value(const ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3e870eaeeef51aeULL;
  static const uint64_t static_value2 = 0x05e735f139f5a34aULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/MoraiWaitForTickSrvResponse";
  }

  static const char* value(const ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "WaitForTickResponse response\n"
"\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/WaitForTickResponse\n"
"# WaitForTickResponse\n"
"# Response after a simulation tick completes in synchronous mode.\n"
"\n"
"bool tick_status  # Tick completion status\n"
"bool pause_status  # Simulation pause status\n"
"uint64 frame  # Current frame number\n"
"\n"
"EgoVehicleStatus vehicle_status  # Ego vehicle state after tick\n"
"string time  # Simulation timestamp\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/EgoVehicleStatus\n"
"# EgoVehicleStatus\n"
"# Status telemetry of the ego vehicle for closed-loop control.\n"
"# Topic: /Ego_topic\n"
"\n"
"Header header\n"
"int32 unique_id  # Object unique id\n"
"geometry_msgs/Vector3 acceleration  # Acceleration vector [m/s^2]\n"
"geometry_msgs/Vector3 position  # Current position in ENU coordinates [m]\n"
"geometry_msgs/Vector3 velocity  # Velocity vector [m/s]\n"
"geometry_msgs/Vector3 angular_velocity  # [deg/s] \n"
"\n"
"float64 heading  # Vehicle heading [deg]\n"
"float32 accel  # Accelerator pedal, range 0~1\n"
"float32 brake  # Brake pedal, range 0~1\n"
"float32 front_steer_angle  # Front wheel angle [deg]\n"
"float32 rear_steer_angle  # Rear wheel angle [deg]\n"
"float32 lateral_offset  # Lateral offset from reference\n"
"\n"
"float32 tire_lateral_force_fl  # Front-left tire lateral force\n"
"float32 tire_lateral_force_fr  # Front-right tire lateral force\n"
"float32 tire_lateral_force_rl  # Rear-left tire lateral force\n"
"float32 tire_lateral_force_rr  # Rear-right tire lateral force\n"
"\n"
"float32 side_slip_angle_fl  # Front-left side slip angle\n"
"float32 side_slip_angle_fr  # Front-right side slip angle\n"
"float32 side_slip_angle_rl  # Rear-left side slip angle\n"
"float32 side_slip_angle_rr  # Rear-right side slip angle\n"
"\n"
"float32 tire_cornering_stiffness_fl  # Front-left cornering stiffness\n"
"float32 tire_cornering_stiffness_fr  # Front-right cornering stiffness\n"
"float32 tire_cornering_stiffness_rl  # Rear-left cornering stiffness\n"
"float32 tire_cornering_stiffness_rr  # Rear-right cornering stiffness\n"
"\n"
"float32 distance_left_lane_boundary  # Distance from left lane boundary [m]\n"
"float32 distance_right_lane_boundary  # Distance from right lane boundary [m]\n"
"float32 cross_track_error  # Distance from lane center, right-positive [m]\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoraiWaitForTickSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::MoraiWaitForTickSrvResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "response: ";
    Printer< ::morai_msgs::WaitForTickResponse_<ContainerAllocator> >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_MORAIWAITFORTICKSRVRESPONSE_H
