// Generated by gencpp from file morai_msgs/MoraiSyncModeCtrlCmdSrvRequest.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_MORAISYNCMODECTRLCMDSRVREQUEST_H
#define MORAI_MSGS_MESSAGE_MORAISYNCMODECTRLCMDSRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <morai_msgs/SyncModeCtrlCmd.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct MoraiSyncModeCtrlCmdSrvRequest_
{
  typedef MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator> Type;

  MoraiSyncModeCtrlCmdSrvRequest_()
    : request()  {
    }
  MoraiSyncModeCtrlCmdSrvRequest_(const ContainerAllocator& _alloc)
    : request(_alloc)  {
  (void)_alloc;
    }



   typedef  ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator>  _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoraiSyncModeCtrlCmdSrvRequest_

typedef ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<std::allocator<void> > MoraiSyncModeCtrlCmdSrvRequest;

typedef boost::shared_ptr< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest > MoraiSyncModeCtrlCmdSrvRequestPtr;
typedef boost::shared_ptr< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest const> MoraiSyncModeCtrlCmdSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "170d29b2262a4aeedd57987f6848475c";
  }

  static const char* value(const ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x170d29b2262a4aeeULL;
  static const uint64_t static_value2 = 0xdd57987f6848475cULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/MoraiSyncModeCtrlCmdSrvRequest";
  }

  static const char* value(const ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "SyncModeCtrlCmd request\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/SyncModeCtrlCmd\n"
"# SyncModeCtrlCmd\n"
"# Vehicle control command for synchronous simulation mode.\n"
"\n"
"uint64 frame  # Frame counter\n"
"\n"
"CtrlCmd command  # Vehicle control command\n"
"\n"
"bool sensor_capture  # true: capture sensor data this frame\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/CtrlCmd\n"
"# CtrlCmd\n"
"# Control command signals for steering, moving, and stopping the ego vehicle.\n"
"# Topic: /ctrl_cmd\n"
"\n"
"int32 longlCmdType  # Control method index (1: Throttle, 2: Velocity, 3: Acceleration)\n"
"\n"
"float64 accel  # Accelerator pedal input, range 0~1\n"
"float64 brake  # Brake pedal input, range 0~1\n"
"float64 front_steer  # Front wheel steer angle [rad]\n"
"float64 rear_steer  # Rear wheel steer angle [rad]\n"
"\n"
"float64 velocity  # Target velocity, active when longlCmdType == 2 [km/h]\n"
"float64 acceleration  # Target acceleration, active when longlCmdType == 3 [m/s^2]\n"
;
  }

  static const char* value(const ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoraiSyncModeCtrlCmdSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "request: ";
    Printer< ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator> >::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_MORAISYNCMODECTRLCMDSRVREQUEST_H
