// Generated by gencpp from file morai_msgs/NpcGhostInfo.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_NPCGHOSTINFO_H
#define MORAI_MSGS_MESSAGE_NPCGHOSTINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct NpcGhostInfo_
{
  typedef NpcGhostInfo_<ContainerAllocator> Type;

  NpcGhostInfo_()
    : unique_id(0)
    , name()
    , position()
    , rpy()
    , steering_angle(0.0)
    , vehicle_speed(0.0)
    , turn_signal(0)
    , brake_light(false)  {
    }
  NpcGhostInfo_(const ContainerAllocator& _alloc)
    : unique_id(0)
    , name(_alloc)
    , position(_alloc)
    , rpy(_alloc)
    , steering_angle(0.0)
    , vehicle_speed(0.0)
    , turn_signal(0)
    , brake_light(false)  {
  (void)_alloc;
    }



   typedef int32_t _unique_id_type;
  _unique_id_type unique_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rpy_type;
  _rpy_type rpy;

   typedef float _steering_angle_type;
  _steering_angle_type steering_angle;

   typedef float _vehicle_speed_type;
  _vehicle_speed_type vehicle_speed;

   typedef uint32_t _turn_signal_type;
  _turn_signal_type turn_signal;

   typedef uint8_t _brake_light_type;
  _brake_light_type brake_light;





  typedef boost::shared_ptr< ::morai_msgs::NpcGhostInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::NpcGhostInfo_<ContainerAllocator> const> ConstPtr;

}; // struct NpcGhostInfo_

typedef ::morai_msgs::NpcGhostInfo_<std::allocator<void> > NpcGhostInfo;

typedef boost::shared_ptr< ::morai_msgs::NpcGhostInfo > NpcGhostInfoPtr;
typedef boost::shared_ptr< ::morai_msgs::NpcGhostInfo const> NpcGhostInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::NpcGhostInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::NpcGhostInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::NpcGhostInfo_<ContainerAllocator1> & lhs, const ::morai_msgs::NpcGhostInfo_<ContainerAllocator2> & rhs)
{
  return lhs.unique_id == rhs.unique_id &&
    lhs.name == rhs.name &&
    lhs.position == rhs.position &&
    lhs.rpy == rhs.rpy &&
    lhs.steering_angle == rhs.steering_angle &&
    lhs.vehicle_speed == rhs.vehicle_speed &&
    lhs.turn_signal == rhs.turn_signal &&
    lhs.brake_light == rhs.brake_light;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::NpcGhostInfo_<ContainerAllocator1> & lhs, const ::morai_msgs::NpcGhostInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::NpcGhostInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::NpcGhostInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::NpcGhostInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::NpcGhostInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::NpcGhostInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::NpcGhostInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::NpcGhostInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b21206763f9d33156cd6eed1aefaa70";
  }

  static const char* value(const ::morai_msgs::NpcGhostInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b21206763f9d331ULL;
  static const uint64_t static_value2 = 0x56cd6eed1aefaa70ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::NpcGhostInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/NpcGhostInfo";
  }

  static const char* value(const ::morai_msgs::NpcGhostInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::NpcGhostInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# NpcGhostInfo\n"
"# Information for a single NPC vehicle in ghost mode.\n"
"\n"
"int32 unique_id  # NPC identifier\n"
"string name  # Model name (e.g., 2016_Kia_Niro(HEV))\n"
"\n"
"geometry_msgs/Vector3 position  # Position in ENU coordinates [m]\n"
"geometry_msgs/Vector3 rpy  # Roll, Pitch, Yaw [deg]\n"
"\n"
"float32 steering_angle  # Steering angle [deg]\n"
"float32 vehicle_speed  # Vehicle speed [km/h]\n"
"uint32 turn_signal  # Turn signal (0: off, 1: left, 2: right, 3: hazard)\n"
"bool brake_light  # Brake light (false: off, true: on)\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::morai_msgs::NpcGhostInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::NpcGhostInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.unique_id);
      stream.next(m.name);
      stream.next(m.position);
      stream.next(m.rpy);
      stream.next(m.steering_angle);
      stream.next(m.vehicle_speed);
      stream.next(m.turn_signal);
      stream.next(m.brake_light);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NpcGhostInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::NpcGhostInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::NpcGhostInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "unique_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.unique_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rpy: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rpy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "steering_angle: ";
    Printer<float>::stream(s, indent + "  ", v.steering_angle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vehicle_speed: ";
    Printer<float>::stream(s, indent + "  ", v.vehicle_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "turn_signal: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.turn_signal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "brake_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brake_light);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_NPCGHOSTINFO_H
