// Generated by gencpp from file morai_msgs/SyncModeCtrlCmd.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_SYNCMODECTRLCMD_H
#define MORAI_MSGS_MESSAGE_SYNCMODECTRLCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <morai_msgs/CtrlCmd.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct SyncModeCtrlCmd_
{
  typedef SyncModeCtrlCmd_<ContainerAllocator> Type;

  SyncModeCtrlCmd_()
    : frame(0)
    , command()
    , sensor_capture(false)  {
    }
  SyncModeCtrlCmd_(const ContainerAllocator& _alloc)
    : frame(0)
    , command(_alloc)
    , sensor_capture(false)  {
  (void)_alloc;
    }



   typedef uint64_t _frame_type;
  _frame_type frame;

   typedef  ::morai_msgs::CtrlCmd_<ContainerAllocator>  _command_type;
  _command_type command;

   typedef uint8_t _sensor_capture_type;
  _sensor_capture_type sensor_capture;





  typedef boost::shared_ptr< ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator> const> ConstPtr;

}; // struct SyncModeCtrlCmd_

typedef ::morai_msgs::SyncModeCtrlCmd_<std::allocator<void> > SyncModeCtrlCmd;

typedef boost::shared_ptr< ::morai_msgs::SyncModeCtrlCmd > SyncModeCtrlCmdPtr;
typedef boost::shared_ptr< ::morai_msgs::SyncModeCtrlCmd const> SyncModeCtrlCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator1> & lhs, const ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator2> & rhs)
{
  return lhs.frame == rhs.frame &&
    lhs.command == rhs.command &&
    lhs.sensor_capture == rhs.sensor_capture;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator1> & lhs, const ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bab2fd41aaffffe3e4fd625ac8bd37f";
  }

  static const char* value(const ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bab2fd41aaffffeULL;
  static const uint64_t static_value2 = 0x3e4fd625ac8bd37fULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/SyncModeCtrlCmd";
  }

  static const char* value(const ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# SyncModeCtrlCmd\n"
"# Vehicle control command for synchronous simulation mode.\n"
"\n"
"uint64 frame  # Frame counter\n"
"\n"
"CtrlCmd command  # Vehicle control command\n"
"\n"
"bool sensor_capture  # true: capture sensor data this frame\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/CtrlCmd\n"
"# CtrlCmd\n"
"# Control command signals for steering, moving, and stopping the ego vehicle.\n"
"# Topic: /ctrl_cmd\n"
"\n"
"int32 longlCmdType  # Control method index (1: Throttle, 2: Velocity, 3: Acceleration)\n"
"\n"
"float64 accel  # Accelerator pedal input, range 0~1\n"
"float64 brake  # Brake pedal input, range 0~1\n"
"float64 front_steer  # Front wheel steer angle [rad]\n"
"float64 rear_steer  # Rear wheel steer angle [rad]\n"
"\n"
"float64 velocity  # Target velocity, active when longlCmdType == 2 [km/h]\n"
"float64 acceleration  # Target acceleration, active when longlCmdType == 3 [m/s^2]\n"
;
  }

  static const char* value(const ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame);
      stream.next(m.command);
      stream.next(m.sensor_capture);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SyncModeCtrlCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::SyncModeCtrlCmd_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "frame: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.frame);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "command: ";
    Printer< ::morai_msgs::CtrlCmd_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sensor_capture: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensor_capture);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_SYNCMODECTRLCMD_H
