// Generated by gencpp from file morai_msgs/VehicleCollision.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_VEHICLECOLLISION_H
#define MORAI_MSGS_MESSAGE_VEHICLECOLLISION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <morai_msgs/ObjectStatus.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct VehicleCollision_
{
  typedef VehicleCollision_<ContainerAllocator> Type;

  VehicleCollision_()
    : crashed_vehicles()  {
    }
  VehicleCollision_(const ContainerAllocator& _alloc)
    : crashed_vehicles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::morai_msgs::ObjectStatus_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::morai_msgs::ObjectStatus_<ContainerAllocator> >> _crashed_vehicles_type;
  _crashed_vehicles_type crashed_vehicles;





  typedef boost::shared_ptr< ::morai_msgs::VehicleCollision_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::VehicleCollision_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleCollision_

typedef ::morai_msgs::VehicleCollision_<std::allocator<void> > VehicleCollision;

typedef boost::shared_ptr< ::morai_msgs::VehicleCollision > VehicleCollisionPtr;
typedef boost::shared_ptr< ::morai_msgs::VehicleCollision const> VehicleCollisionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::VehicleCollision_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::VehicleCollision_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::VehicleCollision_<ContainerAllocator1> & lhs, const ::morai_msgs::VehicleCollision_<ContainerAllocator2> & rhs)
{
  return lhs.crashed_vehicles == rhs.crashed_vehicles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::VehicleCollision_<ContainerAllocator1> & lhs, const ::morai_msgs::VehicleCollision_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::VehicleCollision_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::VehicleCollision_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::VehicleCollision_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::VehicleCollision_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::VehicleCollision_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::VehicleCollision_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::VehicleCollision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b76a1136c5fcb79b704b50b7421616cb";
  }

  static const char* value(const ::morai_msgs::VehicleCollision_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb76a1136c5fcb79bULL;
  static const uint64_t static_value2 = 0x704b50b7421616cbULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::VehicleCollision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/VehicleCollision";
  }

  static const char* value(const ::morai_msgs::VehicleCollision_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::VehicleCollision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# VehicleCollision\n"
"# A single collision event between NPC vehicles.\n"
"\n"
"ObjectStatus[] crashed_vehicles  # List of collided NPC vehicles\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/ObjectStatus\n"
"# ObjectStatus\n"
"# State information for a single object in the simulation.\n"
"\n"
"int32 unique_id  # Object unique id\n"
"int32 type  # Object type (0: Pedestrian, 1: NPC vehicle, 2: Static object, -1: Ego vehicle)\n"
"string name  # Object name\n"
"float64 heading  # Object heading [deg]\n"
"\n"
"geometry_msgs/Vector3 velocity  # Velocity vector [km/h]\n"
"geometry_msgs/Vector3 acceleration  # Acceleration vector [m/s^2]\n"
"geometry_msgs/Vector3 size  # Bounding box size (width, length, height) [m]\n"
"geometry_msgs/Vector3 position  # Position in ENU coordinates [m]\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::morai_msgs::VehicleCollision_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::VehicleCollision_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.crashed_vehicles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleCollision_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::VehicleCollision_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::VehicleCollision_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "crashed_vehicles: ";
    if (v.crashed_vehicles.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.crashed_vehicles.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::morai_msgs::ObjectStatus_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.crashed_vehicles[i]);
    }
    if (v.crashed_vehicles.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_VEHICLECOLLISION_H
