# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from morai_msgs/MoraiSyncModeCtrlCmdSrvRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import morai_msgs.msg

class MoraiSyncModeCtrlCmdSrvRequest(genpy.Message):
  _md5sum = "170d29b2262a4aeedd57987f6848475c"
  _type = "morai_msgs/MoraiSyncModeCtrlCmdSrvRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """SyncModeCtrlCmd request

================================================================================
MSG: morai_msgs/SyncModeCtrlCmd
# SyncModeCtrlCmd
# Vehicle control command for synchronous simulation mode.

uint64 frame  # Frame counter

CtrlCmd command  # Vehicle control command

bool sensor_capture  # true: capture sensor data this frame

================================================================================
MSG: morai_msgs/CtrlCmd
# CtrlCmd
# Control command signals for steering, moving, and stopping the ego vehicle.
# Topic: /ctrl_cmd

int32 longlCmdType  # Control method index (1: Throttle, 2: Velocity, 3: Acceleration)

float64 accel  # Accelerator pedal input, range 0~1
float64 brake  # Brake pedal input, range 0~1
float64 front_steer  # Front wheel steer angle [rad]
float64 rear_steer  # Rear wheel steer angle [rad]

float64 velocity  # Target velocity, active when longlCmdType == 2 [km/h]
float64 acceleration  # Target acceleration, active when longlCmdType == 3 [m/s^2]
"""
  __slots__ = ['request']
  _slot_types = ['morai_msgs/SyncModeCtrlCmd']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       request

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MoraiSyncModeCtrlCmdSrvRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.request is None:
        self.request = morai_msgs.msg.SyncModeCtrlCmd()
    else:
      self.request = morai_msgs.msg.SyncModeCtrlCmd()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Qi6dB().pack(_x.request.frame, _x.request.command.longlCmdType, _x.request.command.accel, _x.request.command.brake, _x.request.command.front_steer, _x.request.command.rear_steer, _x.request.command.velocity, _x.request.command.acceleration, _x.request.sensor_capture))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.request is None:
        self.request = morai_msgs.msg.SyncModeCtrlCmd()
      end = 0
      _x = self
      start = end
      end += 61
      (_x.request.frame, _x.request.command.longlCmdType, _x.request.command.accel, _x.request.command.brake, _x.request.command.front_steer, _x.request.command.rear_steer, _x.request.command.velocity, _x.request.command.acceleration, _x.request.sensor_capture,) = _get_struct_Qi6dB().unpack(str[start:end])
      self.request.sensor_capture = bool(self.request.sensor_capture)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Qi6dB().pack(_x.request.frame, _x.request.command.longlCmdType, _x.request.command.accel, _x.request.command.brake, _x.request.command.front_steer, _x.request.command.rear_steer, _x.request.command.velocity, _x.request.command.acceleration, _x.request.sensor_capture))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.request is None:
        self.request = morai_msgs.msg.SyncModeCtrlCmd()
      end = 0
      _x = self
      start = end
      end += 61
      (_x.request.frame, _x.request.command.longlCmdType, _x.request.command.accel, _x.request.command.brake, _x.request.command.front_steer, _x.request.command.rear_steer, _x.request.command.velocity, _x.request.command.acceleration, _x.request.sensor_capture,) = _get_struct_Qi6dB().unpack(str[start:end])
      self.request.sensor_capture = bool(self.request.sensor_capture)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Qi6dB = None
def _get_struct_Qi6dB():
    global _struct_Qi6dB
    if _struct_Qi6dB is None:
        _struct_Qi6dB = struct.Struct("<Qi6dB")
    return _struct_Qi6dB
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from morai_msgs/MoraiSyncModeCtrlCmdSrvResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import morai_msgs.msg

class MoraiSyncModeCtrlCmdSrvResponse(genpy.Message):
  _md5sum = "4039c80fa74cc3be5f583706bf97e6b0"
  _type = "morai_msgs/MoraiSyncModeCtrlCmdSrvResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """SyncModeResultResponse response


================================================================================
MSG: morai_msgs/SyncModeResultResponse
# SyncModeResultResponse
# Generic result response for sync mode operations.

bool result  # true: success, false: failure
"""
  __slots__ = ['response']
  _slot_types = ['morai_msgs/SyncModeResultResponse']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       response

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MoraiSyncModeCtrlCmdSrvResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.response is None:
        self.response = morai_msgs.msg.SyncModeResultResponse()
    else:
      self.response = morai_msgs.msg.SyncModeResultResponse()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.response.result
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.response is None:
        self.response = morai_msgs.msg.SyncModeResultResponse()
      end = 0
      start = end
      end += 1
      (self.response.result,) = _get_struct_B().unpack(str[start:end])
      self.response.result = bool(self.response.result)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.response.result
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.response is None:
        self.response = morai_msgs.msg.SyncModeResultResponse()
      end = 0
      start = end
      end += 1
      (self.response.result,) = _get_struct_B().unpack(str[start:end])
      self.response.result = bool(self.response.result)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class MoraiSyncModeCtrlCmdSrv(object):
  _type          = 'morai_msgs/MoraiSyncModeCtrlCmdSrv'
  _md5sum = 'e9926504ec40cc3e19da6c7c7a0e8a49'
  _request_class  = MoraiSyncModeCtrlCmdSrvRequest
  _response_class = MoraiSyncModeCtrlCmdSrvResponse
