# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from morai_msgs/EgoVehicleStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class EgoVehicleStatus(genpy.Message):
  _md5sum = "b3d9f65cf9e5cbc5fd966757559f49b2"
  _type = "morai_msgs/EgoVehicleStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# EgoVehicleStatus
# Status telemetry of the ego vehicle for closed-loop control.
# Topic: /Ego_topic

Header header
int32 unique_id  # Object unique id
geometry_msgs/Vector3 acceleration  # Acceleration vector [m/s^2]
geometry_msgs/Vector3 position  # Current position in ENU coordinates [m]
geometry_msgs/Vector3 velocity  # Velocity vector [m/s]
geometry_msgs/Vector3 angular_velocity  # [deg/s] 

float64 heading  # Vehicle heading [deg]
float32 accel  # Accelerator pedal, range 0~1
float32 brake  # Brake pedal, range 0~1
float32 front_steer_angle  # Front wheel angle [deg]
float32 rear_steer_angle  # Rear wheel angle [deg]
float32 lateral_offset  # Lateral offset from reference

float32 tire_lateral_force_fl  # Front-left tire lateral force
float32 tire_lateral_force_fr  # Front-right tire lateral force
float32 tire_lateral_force_rl  # Rear-left tire lateral force
float32 tire_lateral_force_rr  # Rear-right tire lateral force

float32 side_slip_angle_fl  # Front-left side slip angle
float32 side_slip_angle_fr  # Front-right side slip angle
float32 side_slip_angle_rl  # Rear-left side slip angle
float32 side_slip_angle_rr  # Rear-right side slip angle

float32 tire_cornering_stiffness_fl  # Front-left cornering stiffness
float32 tire_cornering_stiffness_fr  # Front-right cornering stiffness
float32 tire_cornering_stiffness_rl  # Rear-left cornering stiffness
float32 tire_cornering_stiffness_rr  # Rear-right cornering stiffness

float32 distance_left_lane_boundary  # Distance from left lane boundary [m]
float32 distance_right_lane_boundary  # Distance from right lane boundary [m]
float32 cross_track_error  # Distance from lane center, right-positive [m]

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','unique_id','acceleration','position','velocity','angular_velocity','heading','accel','brake','front_steer_angle','rear_steer_angle','lateral_offset','tire_lateral_force_fl','tire_lateral_force_fr','tire_lateral_force_rl','tire_lateral_force_rr','side_slip_angle_fl','side_slip_angle_fr','side_slip_angle_rl','side_slip_angle_rr','tire_cornering_stiffness_fl','tire_cornering_stiffness_fr','tire_cornering_stiffness_rl','tire_cornering_stiffness_rr','distance_left_lane_boundary','distance_right_lane_boundary','cross_track_error']
  _slot_types = ['std_msgs/Header','int32','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','float64','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,unique_id,acceleration,position,velocity,angular_velocity,heading,accel,brake,front_steer_angle,rear_steer_angle,lateral_offset,tire_lateral_force_fl,tire_lateral_force_fr,tire_lateral_force_rl,tire_lateral_force_rr,side_slip_angle_fl,side_slip_angle_fr,side_slip_angle_rl,side_slip_angle_rr,tire_cornering_stiffness_fl,tire_cornering_stiffness_fr,tire_cornering_stiffness_rl,tire_cornering_stiffness_rr,distance_left_lane_boundary,distance_right_lane_boundary,cross_track_error

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EgoVehicleStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.unique_id is None:
        self.unique_id = 0
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Vector3()
      if self.position is None:
        self.position = geometry_msgs.msg.Vector3()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Vector3()
      if self.angular_velocity is None:
        self.angular_velocity = geometry_msgs.msg.Vector3()
      if self.heading is None:
        self.heading = 0.
      if self.accel is None:
        self.accel = 0.
      if self.brake is None:
        self.brake = 0.
      if self.front_steer_angle is None:
        self.front_steer_angle = 0.
      if self.rear_steer_angle is None:
        self.rear_steer_angle = 0.
      if self.lateral_offset is None:
        self.lateral_offset = 0.
      if self.tire_lateral_force_fl is None:
        self.tire_lateral_force_fl = 0.
      if self.tire_lateral_force_fr is None:
        self.tire_lateral_force_fr = 0.
      if self.tire_lateral_force_rl is None:
        self.tire_lateral_force_rl = 0.
      if self.tire_lateral_force_rr is None:
        self.tire_lateral_force_rr = 0.
      if self.side_slip_angle_fl is None:
        self.side_slip_angle_fl = 0.
      if self.side_slip_angle_fr is None:
        self.side_slip_angle_fr = 0.
      if self.side_slip_angle_rl is None:
        self.side_slip_angle_rl = 0.
      if self.side_slip_angle_rr is None:
        self.side_slip_angle_rr = 0.
      if self.tire_cornering_stiffness_fl is None:
        self.tire_cornering_stiffness_fl = 0.
      if self.tire_cornering_stiffness_fr is None:
        self.tire_cornering_stiffness_fr = 0.
      if self.tire_cornering_stiffness_rl is None:
        self.tire_cornering_stiffness_rl = 0.
      if self.tire_cornering_stiffness_rr is None:
        self.tire_cornering_stiffness_rr = 0.
      if self.distance_left_lane_boundary is None:
        self.distance_left_lane_boundary = 0.
      if self.distance_right_lane_boundary is None:
        self.distance_right_lane_boundary = 0.
      if self.cross_track_error is None:
        self.cross_track_error = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.unique_id = 0
      self.acceleration = geometry_msgs.msg.Vector3()
      self.position = geometry_msgs.msg.Vector3()
      self.velocity = geometry_msgs.msg.Vector3()
      self.angular_velocity = geometry_msgs.msg.Vector3()
      self.heading = 0.
      self.accel = 0.
      self.brake = 0.
      self.front_steer_angle = 0.
      self.rear_steer_angle = 0.
      self.lateral_offset = 0.
      self.tire_lateral_force_fl = 0.
      self.tire_lateral_force_fr = 0.
      self.tire_lateral_force_rl = 0.
      self.tire_lateral_force_rr = 0.
      self.side_slip_angle_fl = 0.
      self.side_slip_angle_fr = 0.
      self.side_slip_angle_rl = 0.
      self.side_slip_angle_rr = 0.
      self.tire_cornering_stiffness_fl = 0.
      self.tire_cornering_stiffness_fr = 0.
      self.tire_cornering_stiffness_rl = 0.
      self.tire_cornering_stiffness_rr = 0.
      self.distance_left_lane_boundary = 0.
      self.distance_right_lane_boundary = 0.
      self.cross_track_error = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_i13d20f().pack(_x.unique_id, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z, _x.position.x, _x.position.y, _x.position.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.heading, _x.accel, _x.brake, _x.front_steer_angle, _x.rear_steer_angle, _x.lateral_offset, _x.tire_lateral_force_fl, _x.tire_lateral_force_fr, _x.tire_lateral_force_rl, _x.tire_lateral_force_rr, _x.side_slip_angle_fl, _x.side_slip_angle_fr, _x.side_slip_angle_rl, _x.side_slip_angle_rr, _x.tire_cornering_stiffness_fl, _x.tire_cornering_stiffness_fr, _x.tire_cornering_stiffness_rl, _x.tire_cornering_stiffness_rr, _x.distance_left_lane_boundary, _x.distance_right_lane_boundary, _x.cross_track_error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Vector3()
      if self.position is None:
        self.position = geometry_msgs.msg.Vector3()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Vector3()
      if self.angular_velocity is None:
        self.angular_velocity = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 188
      (_x.unique_id, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z, _x.position.x, _x.position.y, _x.position.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.heading, _x.accel, _x.brake, _x.front_steer_angle, _x.rear_steer_angle, _x.lateral_offset, _x.tire_lateral_force_fl, _x.tire_lateral_force_fr, _x.tire_lateral_force_rl, _x.tire_lateral_force_rr, _x.side_slip_angle_fl, _x.side_slip_angle_fr, _x.side_slip_angle_rl, _x.side_slip_angle_rr, _x.tire_cornering_stiffness_fl, _x.tire_cornering_stiffness_fr, _x.tire_cornering_stiffness_rl, _x.tire_cornering_stiffness_rr, _x.distance_left_lane_boundary, _x.distance_right_lane_boundary, _x.cross_track_error,) = _get_struct_i13d20f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_i13d20f().pack(_x.unique_id, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z, _x.position.x, _x.position.y, _x.position.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.heading, _x.accel, _x.brake, _x.front_steer_angle, _x.rear_steer_angle, _x.lateral_offset, _x.tire_lateral_force_fl, _x.tire_lateral_force_fr, _x.tire_lateral_force_rl, _x.tire_lateral_force_rr, _x.side_slip_angle_fl, _x.side_slip_angle_fr, _x.side_slip_angle_rl, _x.side_slip_angle_rr, _x.tire_cornering_stiffness_fl, _x.tire_cornering_stiffness_fr, _x.tire_cornering_stiffness_rl, _x.tire_cornering_stiffness_rr, _x.distance_left_lane_boundary, _x.distance_right_lane_boundary, _x.cross_track_error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.Vector3()
      if self.position is None:
        self.position = geometry_msgs.msg.Vector3()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Vector3()
      if self.angular_velocity is None:
        self.angular_velocity = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 188
      (_x.unique_id, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z, _x.position.x, _x.position.y, _x.position.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.heading, _x.accel, _x.brake, _x.front_steer_angle, _x.rear_steer_angle, _x.lateral_offset, _x.tire_lateral_force_fl, _x.tire_lateral_force_fr, _x.tire_lateral_force_rl, _x.tire_lateral_force_rr, _x.side_slip_angle_fl, _x.side_slip_angle_fr, _x.side_slip_angle_rl, _x.side_slip_angle_rr, _x.tire_cornering_stiffness_fl, _x.tire_cornering_stiffness_fr, _x.tire_cornering_stiffness_rl, _x.tire_cornering_stiffness_rr, _x.distance_left_lane_boundary, _x.distance_right_lane_boundary, _x.cross_track_error,) = _get_struct_i13d20f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_i13d20f = None
def _get_struct_i13d20f():
    global _struct_i13d20f
    if _struct_i13d20f is None:
        _struct_i13d20f = struct.Struct("<i13d20f")
    return _struct_i13d20f
