# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from morai_msgs/MultiEgoSetting.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MultiEgoSetting(genpy.Message):
  _md5sum = "b3e8bbb30459c32caa67e324bd44dff5"
  _type = "morai_msgs/MultiEgoSetting"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# MultiEgoSetting
# Control multiple ego vehicles in the scene with external controllers.
# Topic: /ego_setting

int32 number_of_ego_vehicle  # Number of multi-ego vehicles
int32 camera_index  # Unique index of the viewed vehicle
int32[] ego_index  # Unique indices of multi-ego vehicles to control
float64[] global_position_x  # X-axis position of each multi-ego
float64[] global_position_y  # Y-axis position of each multi-ego
float64[] global_position_z  # Z-axis position (elevation) of each multi-ego
float32[] global_roll  # Roll angle of each multi-ego
float32[] global_pitch  # Pitch angle of each multi-ego
float32[] global_yaw  # Heading angle of each multi-ego
float32[] velocity  # Velocity of each multi-ego
int8[] gear  # Gear (1: Parking, 2: Reverse, 3: Neutral, 4: Drive)
int8[] ctrl_mode  # Control mode (1: keyboard, 16: auto)

float32[] steering_angle  # Steering angle [deg]
float32[] vehicle_speed  # Vehicle speed [km/h]
uint32[] turn_signal  # Turn signal (0: off, 1: left, 2: right, 3: hazard)
bool[] brake_light  # Brake light (false: off, true: on)
"""
  __slots__ = ['number_of_ego_vehicle','camera_index','ego_index','global_position_x','global_position_y','global_position_z','global_roll','global_pitch','global_yaw','velocity','gear','ctrl_mode','steering_angle','vehicle_speed','turn_signal','brake_light']
  _slot_types = ['int32','int32','int32[]','float64[]','float64[]','float64[]','float32[]','float32[]','float32[]','float32[]','int8[]','int8[]','float32[]','float32[]','uint32[]','bool[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       number_of_ego_vehicle,camera_index,ego_index,global_position_x,global_position_y,global_position_z,global_roll,global_pitch,global_yaw,velocity,gear,ctrl_mode,steering_angle,vehicle_speed,turn_signal,brake_light

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MultiEgoSetting, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.number_of_ego_vehicle is None:
        self.number_of_ego_vehicle = 0
      if self.camera_index is None:
        self.camera_index = 0
      if self.ego_index is None:
        self.ego_index = []
      if self.global_position_x is None:
        self.global_position_x = []
      if self.global_position_y is None:
        self.global_position_y = []
      if self.global_position_z is None:
        self.global_position_z = []
      if self.global_roll is None:
        self.global_roll = []
      if self.global_pitch is None:
        self.global_pitch = []
      if self.global_yaw is None:
        self.global_yaw = []
      if self.velocity is None:
        self.velocity = []
      if self.gear is None:
        self.gear = []
      if self.ctrl_mode is None:
        self.ctrl_mode = []
      if self.steering_angle is None:
        self.steering_angle = []
      if self.vehicle_speed is None:
        self.vehicle_speed = []
      if self.turn_signal is None:
        self.turn_signal = []
      if self.brake_light is None:
        self.brake_light = []
    else:
      self.number_of_ego_vehicle = 0
      self.camera_index = 0
      self.ego_index = []
      self.global_position_x = []
      self.global_position_y = []
      self.global_position_z = []
      self.global_roll = []
      self.global_pitch = []
      self.global_yaw = []
      self.velocity = []
      self.gear = []
      self.ctrl_mode = []
      self.steering_angle = []
      self.vehicle_speed = []
      self.turn_signal = []
      self.brake_light = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2i().pack(_x.number_of_ego_vehicle, _x.camera_index))
      length = len(self.ego_index)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.ego_index))
      length = len(self.global_position_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.global_position_x))
      length = len(self.global_position_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.global_position_y))
      length = len(self.global_position_z)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.global_position_z))
      length = len(self.global_roll)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.global_roll))
      length = len(self.global_pitch)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.global_pitch))
      length = len(self.global_yaw)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.global_yaw))
      length = len(self.velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.velocity))
      length = len(self.gear)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(struct.Struct(pattern).pack(*self.gear))
      length = len(self.ctrl_mode)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(struct.Struct(pattern).pack(*self.ctrl_mode))
      length = len(self.steering_angle)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.steering_angle))
      length = len(self.vehicle_speed)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.vehicle_speed))
      length = len(self.turn_signal)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.turn_signal))
      length = len(self.brake_light)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.brake_light))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.number_of_ego_vehicle, _x.camera_index,) = _get_struct_2i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.ego_index = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.global_position_x = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.global_position_y = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.global_position_z = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.global_roll = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.global_pitch = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.global_yaw = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.velocity = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.gear = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.ctrl_mode = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.steering_angle = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.vehicle_speed = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.turn_signal = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.brake_light = s.unpack(str[start:end])
      self.brake_light = list(map(bool, self.brake_light))
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2i().pack(_x.number_of_ego_vehicle, _x.camera_index))
      length = len(self.ego_index)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.ego_index.tostring())
      length = len(self.global_position_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.global_position_x.tostring())
      length = len(self.global_position_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.global_position_y.tostring())
      length = len(self.global_position_z)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.global_position_z.tostring())
      length = len(self.global_roll)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.global_roll.tostring())
      length = len(self.global_pitch)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.global_pitch.tostring())
      length = len(self.global_yaw)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.global_yaw.tostring())
      length = len(self.velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.velocity.tostring())
      length = len(self.gear)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(self.gear.tostring())
      length = len(self.ctrl_mode)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(self.ctrl_mode.tostring())
      length = len(self.steering_angle)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.steering_angle.tostring())
      length = len(self.vehicle_speed)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.vehicle_speed.tostring())
      length = len(self.turn_signal)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.turn_signal.tostring())
      length = len(self.brake_light)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.brake_light.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.number_of_ego_vehicle, _x.camera_index,) = _get_struct_2i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.ego_index = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.global_position_x = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.global_position_y = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.global_position_z = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.global_roll = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.global_pitch = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.global_yaw = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.velocity = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.gear = numpy.frombuffer(str[start:end], dtype=numpy.int8, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.ctrl_mode = numpy.frombuffer(str[start:end], dtype=numpy.int8, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.steering_angle = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.vehicle_speed = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.turn_signal = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.brake_light = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.brake_light = list(map(bool, self.brake_light))
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
