# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from morai_msgs/SyncModeCtrlCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import morai_msgs.msg

class SyncModeCtrlCmd(genpy.Message):
  _md5sum = "9bab2fd41aaffffe3e4fd625ac8bd37f"
  _type = "morai_msgs/SyncModeCtrlCmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# SyncModeCtrlCmd
# Vehicle control command for synchronous simulation mode.

uint64 frame  # Frame counter

CtrlCmd command  # Vehicle control command

bool sensor_capture  # true: capture sensor data this frame

================================================================================
MSG: morai_msgs/CtrlCmd
# CtrlCmd
# Control command signals for steering, moving, and stopping the ego vehicle.
# Topic: /ctrl_cmd

int32 longlCmdType  # Control method index (1: Throttle, 2: Velocity, 3: Acceleration)

float64 accel  # Accelerator pedal input, range 0~1
float64 brake  # Brake pedal input, range 0~1
float64 front_steer  # Front wheel steer angle [rad]
float64 rear_steer  # Rear wheel steer angle [rad]

float64 velocity  # Target velocity, active when longlCmdType == 2 [km/h]
float64 acceleration  # Target acceleration, active when longlCmdType == 3 [m/s^2]
"""
  __slots__ = ['frame','command','sensor_capture']
  _slot_types = ['uint64','morai_msgs/CtrlCmd','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       frame,command,sensor_capture

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SyncModeCtrlCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.frame is None:
        self.frame = 0
      if self.command is None:
        self.command = morai_msgs.msg.CtrlCmd()
      if self.sensor_capture is None:
        self.sensor_capture = False
    else:
      self.frame = 0
      self.command = morai_msgs.msg.CtrlCmd()
      self.sensor_capture = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Qi6dB().pack(_x.frame, _x.command.longlCmdType, _x.command.accel, _x.command.brake, _x.command.front_steer, _x.command.rear_steer, _x.command.velocity, _x.command.acceleration, _x.sensor_capture))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.command is None:
        self.command = morai_msgs.msg.CtrlCmd()
      end = 0
      _x = self
      start = end
      end += 61
      (_x.frame, _x.command.longlCmdType, _x.command.accel, _x.command.brake, _x.command.front_steer, _x.command.rear_steer, _x.command.velocity, _x.command.acceleration, _x.sensor_capture,) = _get_struct_Qi6dB().unpack(str[start:end])
      self.sensor_capture = bool(self.sensor_capture)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Qi6dB().pack(_x.frame, _x.command.longlCmdType, _x.command.accel, _x.command.brake, _x.command.front_steer, _x.command.rear_steer, _x.command.velocity, _x.command.acceleration, _x.sensor_capture))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.command is None:
        self.command = morai_msgs.msg.CtrlCmd()
      end = 0
      _x = self
      start = end
      end += 61
      (_x.frame, _x.command.longlCmdType, _x.command.accel, _x.command.brake, _x.command.front_steer, _x.command.rear_steer, _x.command.velocity, _x.command.acceleration, _x.sensor_capture,) = _get_struct_Qi6dB().unpack(str[start:end])
      self.sensor_capture = bool(self.sensor_capture)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Qi6dB = None
def _get_struct_Qi6dB():
    global _struct_Qi6dB
    if _struct_Qi6dB is None:
        _struct_Qi6dB = struct.Struct("<Qi6dB")
    return _struct_Qi6dB
