// Generated by gencpp from file aim_week1/CustomMsg.msg
// DO NOT EDIT!


#ifndef AIM_WEEK1_MESSAGE_CUSTOMMSG_H
#define AIM_WEEK1_MESSAGE_CUSTOMMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aim_week1
{
template <class ContainerAllocator>
struct CustomMsg_
{
  typedef CustomMsg_<ContainerAllocator> Type;

  CustomMsg_()
    : float_data(0.0)
    , double_data(0.0)
    , float_array()  {
    }
  CustomMsg_(const ContainerAllocator& _alloc)
    : float_data(0.0)
    , double_data(0.0)
    , float_array(_alloc)  {
  (void)_alloc;
    }



   typedef float _float_data_type;
  _float_data_type float_data;

   typedef double _double_data_type;
  _double_data_type double_data;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _float_array_type;
  _float_array_type float_array;





  typedef boost::shared_ptr< ::aim_week1::CustomMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aim_week1::CustomMsg_<ContainerAllocator> const> ConstPtr;

}; // struct CustomMsg_

typedef ::aim_week1::CustomMsg_<std::allocator<void> > CustomMsg;

typedef boost::shared_ptr< ::aim_week1::CustomMsg > CustomMsgPtr;
typedef boost::shared_ptr< ::aim_week1::CustomMsg const> CustomMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aim_week1::CustomMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aim_week1::CustomMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aim_week1::CustomMsg_<ContainerAllocator1> & lhs, const ::aim_week1::CustomMsg_<ContainerAllocator2> & rhs)
{
  return lhs.float_data == rhs.float_data &&
    lhs.double_data == rhs.double_data &&
    lhs.float_array == rhs.float_array;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aim_week1::CustomMsg_<ContainerAllocator1> & lhs, const ::aim_week1::CustomMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aim_week1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::aim_week1::CustomMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aim_week1::CustomMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aim_week1::CustomMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aim_week1::CustomMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aim_week1::CustomMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aim_week1::CustomMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aim_week1::CustomMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85e53a95a789917d4fe5c58d9212cdda";
  }

  static const char* value(const ::aim_week1::CustomMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85e53a95a789917dULL;
  static const uint64_t static_value2 = 0x4fe5c58d9212cddaULL;
};

template<class ContainerAllocator>
struct DataType< ::aim_week1::CustomMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aim_week1/CustomMsg";
  }

  static const char* value(const ::aim_week1::CustomMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aim_week1::CustomMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 float_data\n"
"float64 double_data\n"
"float32[] float_array\n"
"\n"
;
  }

  static const char* value(const ::aim_week1::CustomMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aim_week1::CustomMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.float_data);
      stream.next(m.double_data);
      stream.next(m.float_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aim_week1::CustomMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aim_week1::CustomMsg_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "float_data: ";
    Printer<float>::stream(s, indent + "  ", v.float_data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "double_data: ";
    Printer<double>::stream(s, indent + "  ", v.double_data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "float_array: ";
    if (v.float_array.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.float_array.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.float_array[i]);
    }
    if (v.float_array.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // AIM_WEEK1_MESSAGE_CUSTOMMSG_H
